server:
  port: 8771

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#服务的名称
spring:
  application:
    name: production-service
  zipkin:
    base-url: http://10.211.55.9:9411/
  sleuth:
    sampler:
      probability: 1
      
env: test
branch: test
